# Generated by Django 5.0.6 on 2024-09-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("mensaje", models.TextField(max_length=500)),
            ],
        ),
    ]
